language: bash
os: linux
sudo: enabled
env:
  global:
    - LC_ALL: C.UTF-8
    - LANG: C.UTF-8

install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install snapd
  - sudo snap install lxd --channel 3.0/stable
  - sudo snap install snapcraft --candidate --classic
  - sudo /snap/bin/lxd waitready
  - yes | sudo lxd.migrate
  - sudo /snap/bin/lxd init --auto
  - mkdir -p "$TRAVIS_BUILD_DIR/snaps-cache"
script:
  - export PATH=/snap/bin:$PATH
  - sudo snapcraft build --debug
after_failure:
  - sudo journalctl -u snapd
